name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    
    - name: Build
      run: /bin/bash build/build-on-linux.sh sdk data dep

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:    
        path: ./
    
